import controllerImage from "../assets/xbox.jpg";

export const items = [
  {
    img: controllerImage,
    branch: "EVGA",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
  {
    img: controllerImage,
    branch: "EVGA 2",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
  {
    img: controllerImage,
    branch: "EVGA 3",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
  {
    img: controllerImage,
    branch: "EVGA 4",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
  {
    img: controllerImage,
    branch: "EVGA 5",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
  {
    img: controllerImage,
    branch: "EVGA 6",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
  {
    img: controllerImage,
    branch: "EVGA 7",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
  {
    img: controllerImage,
    branch: "EVGA 8",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
  {
    img: controllerImage,
    branch: "EVGA 9",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
  {
    img: controllerImage,
    branch: "EVGA 10",
    productName: "Nvidia 3060 Ti 12 gb",
    stars: "5 Stars",
    price: 399.99,
    delivery: "Free delivery",
  },
];
